"use client";

import { useMemo, useState } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/agency-button";
import { downloadBlob } from "@/lib/download";
import { faviconSvg, fontPairingForSeed, monogramSvg, paletteForSeed } from "@/lib/brand-kit";
import { operatorSource, sourcesFromLog } from "@/lib/deliverable";
import { useDeliveryRunOrThrow } from "@/components/tools/delivery-run";
import { AgentDock } from "@/components/tools/agent-dock";
import { SourceChip } from "@/components/tools/source-chip";

type KitOutput = { name: string };

export function BrandIdentityKit() {
  const run = useDeliveryRunOrThrow();
  const [name, setName] = useState("");
  const packed = (run.output as KitOutput | null) ?? null;
  const filledName = name || run.brief.trim().split(/\s+/).slice(0, 6).join(" ");
  const seed = packed?.name ?? (filledName.trim() || "Your Brand");
  const palette = useMemo(() => paletteForSeed(seed), [seed]);
  const fonts = useMemo(() => fontPairingForSeed(seed), [seed]);
  const logo = useMemo(() => monogramSvg(seed, 512), [seed]);
  const favicon = useMemo(() => faviconSvg(seed), [seed]);
  const source = operatorSource("Brand name from this run");

  const start = async () => {
    const seedName = filledName.trim();
    if (!seedName) return;
    await run.runScan(
      async (skill) => {
        if (skill.id === "brand.palette") {
          return { payload: paletteForSeed(seedName), sources: [source], detail: "Palette + type" };
        }
        if (skill.id === "brand.kit-zip") {
          return { sources: [source], detail: "Mark, favicon, guide" };
        }
        if (skill.id === "cite-source") {
          return { sources: [source], detail: "Operator-provided name" };
        }
        throw new Error(`Unknown skill ${skill.id}`);
      },
      (log) => ({
        output: { name: seedName },
        deliverable: {
          kind: "kit",
          title: `${seedName} identity kit`,
          artifacts: [{ name: "brand-kit.zip", mime: "application/zip" }],
          sources: sourcesFromLog(log),
          warnings: ["Procedural starter kit — not a trademark-ready custom identity."],
          gates: { download: "locked" },
        },
      }),
    );
  };

  const downloadKit = async () => {
    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();
    zip.file("logo-mark.svg", logo);
    zip.file("favicon.svg", favicon);
    zip.file(
      "brand-guide.txt",
      `${seed} — Brand Guidelines (starter kit)
Generated by Launchabl's Brand Identity Kit tool

PALETTE
Primary:   ${palette[0]}
Secondary: ${palette[1]}
Tint:      ${palette[2]}

TYPE PAIRING
Headings: ${fonts.heading}
Body:     ${fonts.body}
`,
    );
    const content = await zip.generateAsync({ type: "blob" });
    downloadBlob(content, `${seed.replace(/\s+/g, "-").toLowerCase()}-brand-kit.zip`);
  };

  return (
    <AgentDock
      intake={
        <div className="space-y-4">
          <div>
            <label className="text-sm font-medium text-foreground">Brand name</label>
            <input
              value={filledName}
              onChange={(e) => setName(e.target.value)}
              placeholder="Riverside Roasters"
              className="mt-2 w-full rounded-lg border border-border px-3 py-2 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/30"
            />
          </div>
          <Button onClick={start} disabled={run.scanning || !filledName.trim()}>
            Generate kit
          </Button>
        </div>
      }
      review={
        packed ? (
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-[1fr_140px]">
            <div>
              <SourceChip source={source} />
              <p className="mt-4 text-sm font-semibold text-foreground">Palette</p>
              <div className="mt-2 flex gap-2">
                {palette.map((c) => (
                  <div key={c} className="text-center">
                    <span className="block h-10 w-10 rounded-lg" style={{ backgroundColor: c }} />
                    <span className="mt-1 block text-[10px] text-muted-foreground">{c}</span>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-sm text-muted-foreground">
                Headings: <span className="font-medium text-foreground">{fonts.heading}</span>
                <br />
                Body: <span className="font-medium text-foreground">{fonts.body}</span>
              </p>
            </div>
            <div className="flex flex-col items-center rounded-2xl bg-muted p-4">
              <div className="h-28 w-28 rounded-3xl" dangerouslySetInnerHTML={{ __html: logo }} />
            </div>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">No kit yet.</p>
        )
      }
      exportPanel={
        packed ? (
          <Button onClick={downloadKit}>
            <Download className="h-4 w-4" /> Download brand kit (.zip)
          </Button>
        ) : null
      }
    />
  );
}
