"use client";

import { useMemo, useState } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/agency-button";
import { downloadBlob } from "@/lib/download";
import { faviconSvg, fontPairingForSeed, monogramSvg, paletteForSeed } from "@/lib/brand-kit";
import { useDeliveryPhase } from "@/components/tools/delivery-run";
import { ApproveGate } from "@/components/tools/approve-gate";

export function BrandIdentityKit() {
  const [name, setName] = useState("");
  const seed = name.trim() || "Your Brand";
  useDeliveryPhase(name.trim() ? "review" : "submit");

  const palette = useMemo(() => paletteForSeed(seed), [seed]);
  const fonts = useMemo(() => fontPairingForSeed(seed), [seed]);
  const logo = useMemo(() => monogramSvg(seed, 512), [seed]);
  const favicon = useMemo(() => faviconSvg(seed), [seed]);

  const downloadKit = async () => {
    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();
    zip.file("logo-mark.svg", logo);
    zip.file("favicon.svg", favicon);

    const guide = `${seed} — Brand Guidelines (starter kit)
Generated by Launchabl's Brand Identity Kit tool

PALETTE
Primary:   ${palette[0]}
Secondary: ${palette[1]}
Tint:      ${palette[2]}

TYPE PAIRING
Headings: ${fonts.heading}
Body:     ${fonts.body}

LOGO
See logo-mark.svg (also usable as a placeholder favicon: favicon.svg).
This mark is procedurally generated from your brand name and is meant as a
starting point for validation, not a final trademark-ready logo.

NEXT STEP
Launchabl's unlimited plan replaces this starter kit with a fully custom
visual identity system — real logo design, guidelines, and templates.
`;
    zip.file("brand-guide.txt", guide);

    const content = await zip.generateAsync({ type: "blob" });
    downloadBlob(content, `${seed.replace(/\s+/g, "-").toLowerCase()}-brand-kit.zip`);
  };

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_320px]">
      <div>
        <label className="text-sm font-medium text-foreground">Brand name</label>
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Riverside Roasters"
          className="mt-2 w-full rounded-lg border border-border px-3 py-2 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/30"
        />

        <div className="mt-8 grid grid-cols-2 gap-6 sm:grid-cols-3">
          <div>
            <p className="text-sm font-semibold text-foreground">Palette</p>
            <div className="mt-2 flex gap-2">
              {palette.map((c) => (
                <div key={c} className="text-center">
                  <span className="block h-10 w-10 rounded-lg" style={{ backgroundColor: c }} />
                  <span className="mt-1 block text-[10px] text-muted-foreground">{c}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="col-span-2 sm:col-span-2">
            <p className="text-sm font-semibold text-foreground">Type pairing</p>
            <p className="mt-2 text-sm text-muted-foreground">
              Headings: <span className="font-medium text-foreground">{fonts.heading}</span>
              <br />
              Body: <span className="font-medium text-foreground">{fonts.body}</span>
            </p>
          </div>
        </div>

        <ApproveGate ready={Boolean(name.trim())} label="Approve kit">
          <Button className="mt-8" onClick={downloadKit}>
            <Download className="h-4 w-4" /> Download brand kit (.zip)
          </Button>
        </ApproveGate>
      </div>

      <div className="flex flex-col items-center gap-4 rounded-2xl bg-muted p-6">
        <p className="self-start text-sm font-semibold text-foreground">Logo mark preview</p>
        <div className="h-40 w-40 rounded-3xl" dangerouslySetInnerHTML={{ __html: logo }} />
      </div>
    </div>
  );
}
